version: '3'

services:
  lp.userprofile.api:
    image: lp.userprofile.api
    build:
      context: ./LP.UserProfile.Api
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: microsoft/mssql-server-windows
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  lp.eventsystem.api:
    image: lp.eventsystem.api
    build:
      context: .
      dockerfile: LP.EventSystem.Api\Dockerfile

