version: '3'

services:
  lp.userprofile.api:
    image: lp.userprofile.api
    build:
      context: ./LP.UserProfile.Api
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: microsoft/mssql-server-linux
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
  lp.clients.web:
    image: lp.clients.web
    build:
      context: ./../LP.Clients.Web
      dockerfile: Dockerfile

  lp.clients.web.endpoint:
    image: lp.clients.web.endpoint
    build:
      context: ./LP.Clients.Web.Endpoint
      dockerfile: Dockerfile
