FROM microsoft/aspnetcore:2.0
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0
WORKDIR /src
COPY *.sln ./
COPY LP.EventSystem.Api/LP.EventSystem.Api.csproj LP.EventSystem.Api/
RUN dotnet restore
COPY . .
WORKDIR /src/LP.EventSystem.Api
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "LP.EventSystem.Api.dll"]
